GET http://localhost:8899/api/auth/xxx
###
GET http://localhost:8899/api/post/
###
# POST https://localhost:8899/api/auth/login

POST http://localhost:8899/api/auth/loginfdfd
//path err
###

POST http://localhost:8899/api/auth/login
Content-Type: application/json

 {
    "identity": "tap@cc21.web",
    "password": "a1234"
 }
 ###